#!/usr/bin/env bash
# Install nginx on web server; Nginx should be listening on port 80

sudo apt-get update -y
sudo apt-get install -y nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx start
