#!/usr/bin/env bash
# Script to install and configure HAproxy on lb-01 server

sudo apt-get update
sudo apt-get install haproxy -y

cat << EOF > /etc/haproxy/haproxy.cfg
global
        daemon
        maxconn 256
defaults
        mode http
        timeout connect 5000ms
        timeout client 50000ms
        timeout server 50000ms
frontend http-in
        bind *:80
        default_backend servers
backend servers
        balance roundrobin
        server 158371-web-01 52.3.251.92:80 check
        server 158371-web-02 34.204.81.7:80 check
EOF

echo "52.3.251.92" > /etc/hostname
echo "34.204.81.7" >> /etc/hostname

sed -i 's/ENABLED=0/ENABLED=1/g' /etc/default/haproxy

# Start HAproxy
/etc/init.d/haproxy start
