#!/usr/bin/env bash
# Fizzbuzz
i=1
for i in {1..100}
do
	if [ $(( i%15 )) -eq 0 ]
    	then
        	echo "Fizzbuzz"
    	elif [ $(( i%5 )) -eq 0 ]
    	then
        	echo "Buzz"
    	elif [ $(( i%3 )) -eq 0 ]
    	then
        	echo "Fizz"
    	else
        	echo "$i"
    	fi
	i=$((i + 1))
done
i=$i
