#!/usr/bin/env bash
# Fixes a server to run nginx as the nginx user listening to port 8080
pkill -f apache2
chmod 644 /etc/nginx/nginx.conf
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-enabled/default
sudo -u nginx service nginx restart
